backend:
  name: github
  repo: ServicesBI/Site
  branch: main
  auth_type: implicit
  app_id: Ov23li7gJbK5PMf3WZJJ


media_folder: "imagem/uploads"
public_folder: "/imagem/uploads"

site_url: https://site-ehf.pages.dev
display_url: https://site-ehf.pages.dev

publish_mode: editorial_workflow
