backend:
  name: github
  repo: ServicesBI/Site
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }

  - name: "services"
    label: "Serviços"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }

