site_url: https://servicesbi-auth.netlify.app
display_url: https://servicesbi.com.br

backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"



collections:
  - name: "home"
    label: "Home"
    files:
      - file: "content/cms/pages/Home/home.yml"
        label: "Página Home"
        name: "home"
        fields:
          - { label: "Título do Cabeçalho", name: "cabecalho.titulo", widget: "string" }
          - { label: "Subtítulo do Cabeçalho", name: "cabecalho.subtitulo", widget: "string" }

          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Imagem", name: "imagem", widget: "image" }
              - { label: "Texto Destaque", name: "texto_destaque", widget: "string" }

          - label: "Serviços"
            name: "servicos"
            widget: "object"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - label: "Cartões"
                name: "cartoes"
                widget: "list"
                fields:
                  - { label: "Título", name: "titulo", widget: "string" }
                  - { label: "Descrição", name: "descricao", widget: "text" }
                  - { label: "Imagem", name: "imagem", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }

          - label: "Projetos"
            name: "projetos"
            widget: "object"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - label: "Cartões"
                name: "cartoes"
                widget: "list"
                fields:
                  - { label: "Título", name: "titulo", widget: "string" }
                  - { label: "Descrição", name: "descricao", widget: "text" }
                  - { label: "Imagem", name: "imagem", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
